export const LOAD_FILMS = 'LOAD_FILMS';
export const ADD_FILM = 'ADD_FILM';
export const UPDATE_FILM = 'UPDATE_FILM';
export const DELETE_FILM = 'DELETE_FILM';

export const LOAD_FILMS_SUCCESS ='LOAD_FILMS_SUCCESS';
export const SAVE_FILMS_SUCCESS ='SAVE_FILMS_SUCCESS';
export const DELETE_FILM_SUCCESS ='DELETE_FILM_SUCCESS';


export const LOAD_AUTHORS_SUCCESS ='LOAD_AUTHORS_SUCCESS';
export const LOAD_USERS_SUCCESS ='LOAD_USERS_SUCCESS';

export const ADD_TODO = 'ADD_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const EDIT_TODO = 'EDIT_TODO';
export const COMPLETE_TODO = 'COMPLETE_TODO';
export const COMPLETE_ALL = 'COMPLETE_ALL';
export const CLEAR_COMPLETED = 'CLEAR_COMPLETED';
