export const ADD_FILM_SUCCESS ='ADD_FILM_SUCCESS';
export const UPDATE_FILM_SUCCESS ='UPDATE_FILM_SUCCESS';
export const LOAD_FILMS_SUCCESS ='LOAD_FILMS_SUCCESS';
export const DELETE_FILM_SUCCESS ='DELETE_FILM_SUCCESS';


export const LOAD_AUTHORS_SUCCESS ='LOAD_AUTHORS_SUCCESS';
export const LOAD_USERS_SUCCESS ='LOAD_USERS_SUCCESS';